# Sweetener
# Helper class/functions for getting/processing CSDB data
# Channing Bellamy (BLLCHA013)
# University of Cape Town

import os

def load_dump(lines: list[str]) -> list[dict]:
    dump_item_template: dict = { 'CSDB_ID': "",
                'CNMR SPECTRUM': "",
                'TEMPERATURE': -1,
                'SOLVENT': "",
                'HNMR SPECTRUM': "",
                '1H TEMPERATURE': -1,
                'STRUCTURE': "" }

    dump_item = dump_item_template.copy()
    dump_data: list[dict] = []

    for line in lines:
        if line.startswith("CSDB_ID: "):
            if len(dump_item.get('CSDB_ID')) > 0:
                dump_data.append(dump_item)
            dump_item = dump_item_template.copy()
            dump_item['CSDB_ID'] = line.strip()[line.find(": ") + 2:]
        elif line.startswith("CNMR SPECTRUM: "):
            dump_item['CNMR SPECTRUM'] = line.strip()[line.find(": ") + 2:]
        elif line.startswith("TEMPERATURE: "):
                temperature = line.strip()[line.find(": ") + 2:]
                try:
                    dump_item['TEMPERATURE'] = int(temperature)
                except:
                    dump_item['TEMPERATURE'] = -1
        elif line.startswith("SOLVENT: "):
            dump_item['SOLVENT'] = line.strip()[line.find(": ") + 2:]
        elif line.startswith("HNMR SPECTRUM: "):
            dump_item['HNMR SPECTRUM'] = line.strip()[line.find(": ") + 2:]
        elif line.startswith("1H TEMPERATURE: "):
                temperature = line.strip()[line.find(": ") + 2:]
                try:
                    dump_item['1H TEMPERATURE'] = int(temperature)
                except:
                    dump_item['1H TEMPERATURE'] = -1
        elif line.startswith("STRUCTURE: "):
            dump_item['STRUCTURE'] = line.strip()[line.find(": ") + 2:]

    return dump_data

def split_pdb(lines: list[str]) -> list[list[str]]:
    foundStart = False
    foundEnd = False
    newLines = []
    returnList = []
    for line in lines:
        if foundEnd:
            returnList.append(newLines.copy())
            newLines = []
            foundStart = False
            foundEnd = False
            continue
        if line.startswith("<PDB>"):
            foundStart = True
            continue
        if line.startswith("</PDB>"):
            foundEnd = True
            continue
        if foundStart:
            newLines.append(line)
    return returnList

def is_valid_pdb(lines: list[str]) -> bool:
    checks = { 'AUTHOR header': False,
               'COMPND header': False,
                'PDB MASTER': False,
                'PDB END': False,
                'No duplicates': True }
    for line in lines:
        if line.startswith("AUTHOR    GENERATED BY OPENBABEL 2.4.1, RESIDUE ASSIGNMENT BY CARBOHYDRATE STRUCTURE DATABASE"):
            if checks['AUTHOR header'] == False:
                checks['AUTHOR header'] = True
            else:
                checks['No duplicates'] = False
            continue
        if line.startswith("COMPND    CSDB linear = "):
            if checks['COMPND header'] == False:
                checks['COMPND header'] = True
            else:
                checks['No duplicates'] = False
            continue
        if line.startswith("MASTER"):
            if checks['PDB MASTER'] == False:
                checks['PDB MASTER'] = True
            else:
                checks['No duplicates'] = False
            continue
        if line.strip().startswith("END"):
            if checks['PDB END'] == False:
                checks['PDB END'] = True
            else:
                checks['No duplicates'] = False
            continue

    if all(checks.values()):
        return True

    return False

def is_valid_pdb_multi(lines: list[str]) -> bool:
    for line in lines:
        if line.startswith("Errors:") and not line.startswith("Errors: none"):
            return False
    pdbs = split_pdb(lines)
    if len(pdbs) == 0:
        return False
    for pdb in pdbs:
        isValid = is_valid_pdb(pdb)
        if not isValid:
            return False
    return True

def remark_present_pdb(lines: list[str]) -> bool:
    checks = { 'REMARK present': False }
    for line in lines:
        if line.startswith("REMARK 300 "):
            checks['REMARK present'] = True
            break

    if all(checks.values()):
        return True

    return False

def is_valid_mol(lines: list[str]) -> bool:
    checks = { 'CSDB linear header': False,
               'REStLESS header': False,
                'Mapping header': False,
                'MOL header': False,
                'MOL end': False,
                'No duplicates': True }
    for line in lines:
        if line.startswith("CSDB linear = "):
            if checks['CSDB linear header'] == False:
                checks['CSDB linear header'] = True
            else:
                checks['No duplicates'] = False
            continue
        if line.startswith("MOL was produced by REStLESS, a part of CSDB (http://csdb.glycoscience.ru)"):
            if checks['REStLESS header'] == False:
                checks['REStLESS header'] = True
            else:
                checks['No duplicates'] = False
            continue
        if line.startswith("Mapping: #"):
            if checks['Mapping header'] == False:
                checks['Mapping header'] = True
            else:
                checks['No duplicates'] = False
            continue
        if line.strip().endswith("0999 V2000"):
            if checks['MOL header'] == False:
                checks['MOL header'] = True
            else:
                checks['No duplicates'] = False
            continue
        if line.startswith("M  END"):
            if checks['MOL end'] == False:
                checks['MOL end'] = True
            else:
                checks['No duplicates'] = False
            continue
    
    if all(checks.values()):
        return True

    return False

def delete_invalid_pdb(path: str):
    print(f"INFO: checking for invalid PDB files...")
    for entry in os.scandir(path):
        if entry.is_file():
            file = open(entry.path)
            lines = file.readlines()
            valid = is_valid_pdb_multi(lines)
            if not valid:
                os.remove(entry.path)
                print(f"WARNING: deleted invalid PDB file at {entry.path}")

def delete_invalid_pdbg(path: str):
    print(f"INFO: checking for invalid PDBG files...")
    for entry in os.scandir(path):
        if entry.is_file():
            file = open(entry.path)
            lines = file.readlines()
            valid = is_valid_pdb_multi(lines)
            if not valid:
                os.remove(entry.path)
                print(f"WARNING: deleted invalid PDBG file at {entry.path}")

def delete_invalid_mol(path: str):
    print(f"INFO: checking for invalid MOL files...")
    for entry in os.scandir(path):
        if entry.is_file():
            file = open(entry.path)
            lines = file.readlines()
            valid = is_valid_mol(lines)
            if not valid:
                os.remove(entry.path)
                print(f"WARNING: deleted invalid MOL file at {entry.path}")
